/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemStatus = IDL.Variant({ 'done' : IDL.Null, 'todo' : IDL.Null });
export const Item = IDL.Record({
  'id' : IDL.Nat,
  'status' : ItemStatus,
  'title' : IDL.Text,
});

export const idlService = IDL.Service({
  'createItem' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'updateItem' : IDL.Func([IDL.Nat, IDL.Text, ItemStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemStatus = IDL.Variant({ 'done' : IDL.Null, 'todo' : IDL.Null });
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'status' : ItemStatus,
    'title' : IDL.Text,
  });
  
  return IDL.Service({
    'createItem' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'updateItem' : IDL.Func([IDL.Nat, IDL.Text, ItemStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };