/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlayerRecentGame {
    fieldGoalAttempts: number;
    date: string;
    minutes: number;
    usageRate: number;
    points: number;
    opponent: string;
}
export interface Player {
    id: PlayerId;
    name: string;
    team: string;
    jerseyNumber: string;
    injuryStatus: string;
    position: string;
}
export type Result_2 = {
    __kind__: "ok";
    ok: GamesResponse;
} | {
    __kind__: "err";
    err: ApiError;
};
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface LineMovement {
    openingSpread?: number;
    currentSpread?: number;
    spreadMove: number;
    openingTotal?: number;
    currentTotal?: number;
    totalMove: number;
    steamAlert: boolean;
    sharpSide: string;
}
export interface RestAdvantage {
    homeRestDays: bigint;
    awayRestDays: bigint;
    advantage: string;
    impactDescription: string;
}
export interface SituationalAngle {
    name: string;
    description: string;
    edge: string;
    confidence: bigint;
}
export interface GameInvestigation {
    game: Game;
    odds: Array<OddsLine>;
    injuries: Array<InjuryReport>;
    discrepancies: Array<Discrepancy>;
    homeTeamStats: TeamStats;
    awayTeamStats: TeamStats;
    lineMovement?: LineMovement;
    restAdvantage?: RestAdvantage;
    situationalAngles: Array<SituationalAngle>;
    refereeProfile?: RefereeProfile;
}
export interface Game {
    id: GameId;
    status: GameStatus;
    venue: string;
    displayTime: string;
    homeTeam: Team;
    odds: Array<OddsLine>;
    series?: string;
    awayTeam: Team;
    gameTime: string;
}
export interface InjuryReport {
    status: string;
    playerId: PlayerId;
    team: string;
    description: string;
    updatedAt: string;
    playerName: string;
}
export interface BetHistoryStats {
    lostBets: bigint;
    wonBets: bigint;
    totalBets: bigint;
    pendingBets: bigint;
    winRate: number;
}
export interface PlayerProp {
    seasonAvgPoints: number;
    player: Player;
    seasonUsageRate: number;
    matchupDefRating?: number;
    seasonAvgMinutes: number;
    propLines: Array<PropLine>;
    confidenceReport?: ConfidenceReport;
    backToBack: boolean;
    recentGames: Array<PlayerRecentGame>;
    homeAwaySplit: number;
}
export type Result_5 = {
    __kind__: "ok";
    ok: GameTotal;
} | {
    __kind__: "err";
    err: ApiError;
};
export interface ScoringTrend {
    result: string;
    overUnder: number;
    teamTotal: number;
    date: string;
    gameTotal: number;
    opponent: string;
}
export type TeamId = string;
export type Result_1 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: ApiError;
};
export type Result_4 = {
    __kind__: "ok";
    ok: Array<OddsLine>;
} | {
    __kind__: "err";
    err: ApiError;
};
export type PlayerId = string;
export interface RefereeProfile {
    overRate?: number;
    name: string;
    avgFoulsPerGame?: number;
    avgFreeThrowsPerGame?: number;
    tendency: string;
}
export interface PaceProfile {
    defensiveEfficiency: number;
    pace: number;
    avgPointsAgainst: number;
    avgPointsFor: number;
    offensiveEfficiency: number;
    teamId: TeamId;
    last5Avg: number;
}
export interface GamesResponse {
    gamesDate: string;
    isUpcomingDate: boolean;
    games: Array<Game>;
}
export type GameId = string;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ConfidenceReport {
    keyFactors: Array<string>;
    projectedPoints?: number;
    reasoning: string;
    score: bigint;
    grade: string;
    recommendation: string;
}
export interface OddsLine {
    homeMoneyline?: bigint;
    overUnder?: number;
    awaySpreadOdds?: bigint;
    awayMoneyline?: bigint;
    overOdds?: bigint;
    awaySpread?: number;
    homeSpreadOdds?: bigint;
    homeSpread?: number;
    bookmaker: string;
    underOdds?: bigint;
    updatedAt: string;
}
export interface ApiStatus {
    lastBdlCallStatus?: string;
    oddsApiConfigured: boolean;
    openAiConfigured: boolean;
    bdlApiConfigured: boolean;
    lastOddsApiCallStatus?: string;
}
export interface Team {
    id: TeamId;
    city: string;
    name: string;
    abbreviation: string;
    record: string;
}
export type Result_6 = {
    __kind__: "ok";
    ok: GameInvestigation;
} | {
    __kind__: "err";
    err: ApiError;
};
export interface TotalsConfidenceReport {
    overUnderEdge: string;
    keyFactors: Array<string>;
    reasoning: string;
    score: bigint;
    projectedTotal?: number;
    grade: string;
    recommendation: string;
}
export interface TeamStats {
    pace?: number;
    recentForm: Array<bigint>;
    homeAwayRecord: string;
    defensiveRating?: number;
    teamId: TeamId;
    restDays: bigint;
    offensiveRating?: number;
    pointsPerGame?: number;
}
export interface PlayerPropsAnalysis {
    gameId: GameId;
    players: Array<PlayerProp>;
    analysisGeneratedAt: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Result = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: ApiError;
};
export type Result_3 = {
    __kind__: "ok";
    ok: PlayerPropsAnalysis;
} | {
    __kind__: "err";
    err: ApiError;
};
export interface PropLine {
    overOdds: bigint;
    line: number;
    bookmaker: string;
    underOdds: bigint;
}
export type ApiError = {
    __kind__: "networkError";
    networkError: string;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "parseError";
    parseError: string;
} | {
    __kind__: "rateLimited";
    rateLimited: string;
} | {
    __kind__: "unavailable";
    unavailable: string;
};
export interface GameTotal {
    homePace: PaceProfile;
    gameId: GameId;
    refereeProfile?: RefereeProfile;
    impliedTotal?: number;
    projectedTotal?: number;
    recentTrends: Array<ScoringTrend>;
    confidenceReport?: TotalsConfidenceReport;
    awayPace: PaceProfile;
    injuryImpact: string;
}
export interface Discrepancy {
    gap: number;
    minValue: number;
    minBook: string;
    betType: string;
    maxBook: string;
    maxValue: number;
}
export interface BetRecommendation {
    id: string;
    status: BetStatus;
    result?: string;
    homeTeam: string;
    gameResult?: string;
    betType: BetType;
    gameId: GameId;
    description: string;
    reasoning: string;
    updatedAt?: bigint;
    recommendedAt: bigint;
    awayTeam: string;
    gameDate: string;
    preGameOdds?: string;
    confidence: bigint;
    closingLine?: string;
    clvScore?: number;
}
export enum BetStatus {
    won = "won",
    cancelled = "cancelled",
    pending = "pending",
    lost = "lost",
    push = "push"
}
export enum BetType {
    gameTotal = "gameTotal",
    playerProp = "playerProp",
    spread = "spread"
}
export enum GameStatus {
    final_ = "final",
    scheduled = "scheduled",
    inProgress = "inProgress",
    postponed = "postponed"
}
export interface backendInterface {
    getApiStatus(): Promise<ApiStatus>;
    getBetHistory(): Promise<Array<BetRecommendation>>;
    getBetHistoryStats(): Promise<BetHistoryStats>;
    getOpeningLine(gameId: string): Promise<string | undefined>;
    recordOpeningLine(gameId: string, spread: string, total: string, homeML: string): Promise<void>;
    saveBetRecommendation(rec: BetRecommendation): Promise<Result_1>;
    updateBetOutcome(id: string, status: BetStatus, gameResult: string | null): Promise<Result>;
    updateClosingLine(id: string, closingLine: string, preGameLine: string): Promise<Result>;
}
import type { ApiError as _ApiError, ApiStatus as _ApiStatus, BetRecommendation as _BetRecommendation, BetStatus as _BetStatus, BetType as _BetType, ConfidenceReport as _ConfidenceReport, Discrepancy as _Discrepancy, Game as _Game, GameId as _GameId, GameInvestigation as _GameInvestigation, GameStatus as _GameStatus, GameTotal as _GameTotal, GamesResponse as _GamesResponse, InjuryReport as _InjuryReport, LineMovement as _LineMovement, OddsLine as _OddsLine, PaceProfile as _PaceProfile, Player as _Player, PlayerProp as _PlayerProp, PlayerPropsAnalysis as _PlayerPropsAnalysis, PlayerRecentGame as _PlayerRecentGame, PropLine as _PropLine, RefereeProfile as _RefereeProfile, RestAdvantage as _RestAdvantage, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, ScoringTrend as _ScoringTrend, SituationalAngle as _SituationalAngle, Team as _Team, TeamId as _TeamId, TeamStats as _TeamStats, TotalsConfidenceReport as _TotalsConfidenceReport } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getApiStatus(): Promise<ApiStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiStatus();
                return from_candid_ApiStatus_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiStatus();
            return from_candid_ApiStatus_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBetHistory(): Promise<Array<BetRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBetHistory();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBetHistory();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBetHistoryStats(): Promise<BetHistoryStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getBetHistoryStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBetHistoryStats();
            return result;
        }
    }
    async getGameInvestigation(arg0: GameId, arg1: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameInvestigation(arg0, arg1);
                return from_candid_Result_6_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameInvestigation(arg0, arg1);
            return from_candid_Result_6_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameTotalsAnalysis(arg0: GameId, arg1: string, arg2: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameTotalsAnalysis(arg0, arg1, arg2);
                return from_candid_Result_5_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameTotalsAnalysis(arg0, arg1, arg2);
            return from_candid_Result_5_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMultiBookOdds(arg0: GameId): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.getMultiBookOdds(arg0);
                return from_candid_Result_4_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMultiBookOdds(arg0);
            return from_candid_Result_4_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerPropsAnalysis(arg0: GameId): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerPropsAnalysis(arg0);
                return from_candid_Result_3_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerPropsAnalysis(arg0);
            return from_candid_Result_3_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropsAIAnalysis(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropsAIAnalysis(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropsAIAnalysis(arg0, arg1);
            return result;
        }
    }
    async getTodaysGames(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysGames();
                return from_candid_Result_2_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysGames();
            return from_candid_Result_2_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalsAIAnalysis(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalsAIAnalysis(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalsAIAnalysis(arg0, arg1);
            return result;
        }
    }
    async isBdlApiConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isBdlApiConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isBdlApiConfigured();
            return result;
        }
    }
    async isOddsApiConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOddsApiConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOddsApiConfigured();
            return result;
        }
    }
    async isOpenAIConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOpenAIConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOpenAIConfigured();
            return result;
        }
    }
    async saveBetRecommendation(arg0: BetRecommendation): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBetRecommendation(to_candid_BetRecommendation_n55(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBetRecommendation(to_candid_BetRecommendation_n55(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async setBdlApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBdlApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBdlApiKey(arg0);
            return result;
        }
    }
    async setOddsApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOddsApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOddsApiKey(arg0);
            return result;
        }
    }
    async setOpenAIApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenAIApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenAIApiKey(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBetOutcome(arg0: string, arg1: BetStatus, arg2: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBetOutcome(arg0, to_candid_BetStatus_n57(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBetOutcome(arg0, to_candid_BetStatus_n57(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClosingLine(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClosingLine(arg0, arg1, arg2);
                return from_candid_Result_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClosingLine(arg0, arg1, arg2);
            return from_candid_Result_n64(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApiError_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiError): ApiError {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ApiStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiStatus): ApiStatus {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_BetRecommendation_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BetRecommendation): BetRecommendation {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_BetStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BetStatus): BetStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_BetType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BetType): BetType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ConfidenceReport_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConfidenceReport): ConfidenceReport {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_GameInvestigation_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameInvestigation): GameInvestigation {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_GameStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_GameTotal_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameTotal): GameTotal {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Game_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Game): Game {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_GamesResponse_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GamesResponse): GamesResponse {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_OddsLine_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OddsLine): OddsLine {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerProp_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProp): PlayerProp {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerPropsAnalysis_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerPropsAnalysis): PlayerPropsAnalysis {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_RefereeProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RefereeProfile): RefereeProfile {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_TeamStats_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamStats): TeamStats {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TotalsConfidenceReport_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TotalsConfidenceReport): TotalsConfidenceReport {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_lineMovement(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LineMovement]): LineMovement | null {
    if (value.length === 0) return null;
    const v = value[0];
    return {
        openingSpread: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, v.openingSpread)),
        currentSpread: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, v.currentSpread)),
        spreadMove: v.spreadMove,
        openingTotal: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, v.openingTotal)),
        currentTotal: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, v.currentTotal)),
        totalMove: v.totalMove,
        steamAlert: v.steamAlert,
        sharpSide: v.sharpSide,
    };
}
function from_candid_opt_restAdvantage(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestAdvantage]): RestAdvantage | null {
    if (value.length === 0) return null;
    const v = value[0];
    return {
        homeRestDays: v.homeRestDays,
        awayRestDays: v.awayRestDays,
        advantage: v.advantage,
        impactDescription: v.impactDescription,
    };
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RefereeProfile]): RefereeProfile | null {
    return value.length === 0 ? null : from_candid_RefereeProfile_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TotalsConfidenceReport]): TotalsConfidenceReport | null {
    return value.length === 0 ? null : from_candid_TotalsConfidenceReport_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ConfidenceReport]): ConfidenceReport | null {
    return value.length === 0 ? null : from_candid_ConfidenceReport_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameInvestigation): GameInvestigation {
    return {
        game: from_candid_Game_n16(_uploadFile, _downloadFile, value.game),
        odds: from_candid_vec_n20(_uploadFile, _downloadFile, value.odds),
        injuries: value.injuries,
        discrepancies: value.discrepancies,
        homeTeamStats: from_candid_TeamStats_n24(_uploadFile, _downloadFile, value.homeTeamStats),
        awayTeamStats: from_candid_TeamStats_n24(_uploadFile, _downloadFile, value.awayTeamStats),
        lineMovement: record_opt_to_undefined(from_candid_opt_lineMovement(_uploadFile, _downloadFile, value.lineMovement)),
        restAdvantage: record_opt_to_undefined(from_candid_opt_restAdvantage(_uploadFile, _downloadFile, value.restAdvantage)),
        situationalAngles: value.situationalAngles,
        refereeProfile: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.refereeProfile)),
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GameId;
    status: _GameStatus;
    venue: string;
    displayTime: string;
    homeTeam: _Team;
    odds: Array<_OddsLine>;
    series: [] | [string];
    awayTeam: _Team;
    gameTime: string;
}): {
    id: GameId;
    status: GameStatus;
    venue: string;
    displayTime: string;
    homeTeam: Team;
    odds: Array<OddsLine>;
    series?: string;
    awayTeam: Team;
    gameTime: string;
} {
    return {
        id: value.id,
        status: from_candid_GameStatus_n18(_uploadFile, _downloadFile, value.status),
        venue: value.venue,
        displayTime: value.displayTime,
        homeTeam: value.homeTeam,
        odds: from_candid_vec_n20(_uploadFile, _downloadFile, value.odds),
        series: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.series)),
        awayTeam: value.awayTeam,
        gameTime: value.gameTime
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastBdlCallStatus: [] | [string];
    oddsApiConfigured: boolean;
    openAiConfigured: boolean;
    bdlApiConfigured: boolean;
    lastOddsApiCallStatus: [] | [string];
}): {
    lastBdlCallStatus?: string;
    oddsApiConfigured: boolean;
    openAiConfigured: boolean;
    bdlApiConfigured: boolean;
    lastOddsApiCallStatus?: string;
} {
    return {
        lastBdlCallStatus: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.lastBdlCallStatus)),
        oddsApiConfigured: value.oddsApiConfigured,
        openAiConfigured: value.openAiConfigured,
        bdlApiConfigured: value.bdlApiConfigured,
        lastOddsApiCallStatus: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.lastOddsApiCallStatus))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    homeMoneyline: [] | [bigint];
    overUnder: [] | [number];
    awaySpreadOdds: [] | [bigint];
    awayMoneyline: [] | [bigint];
    overOdds: [] | [bigint];
    awaySpread: [] | [number];
    homeSpreadOdds: [] | [bigint];
    homeSpread: [] | [number];
    bookmaker: string;
    underOdds: [] | [bigint];
    updatedAt: string;
}): {
    homeMoneyline?: bigint;
    overUnder?: number;
    awaySpreadOdds?: bigint;
    awayMoneyline?: bigint;
    overOdds?: bigint;
    awaySpread?: number;
    homeSpreadOdds?: bigint;
    homeSpread?: number;
    bookmaker: string;
    underOdds?: bigint;
    updatedAt: string;
} {
    return {
        homeMoneyline: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.homeMoneyline)),
        overUnder: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.overUnder)),
        awaySpreadOdds: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.awaySpreadOdds)),
        awayMoneyline: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.awayMoneyline)),
        overOdds: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.overOdds)),
        awaySpread: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.awaySpread)),
        homeSpreadOdds: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.homeSpreadOdds)),
        homeSpread: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.homeSpread)),
        bookmaker: value.bookmaker,
        underOdds: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.underOdds)),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pace: [] | [number];
    recentForm: Array<bigint>;
    homeAwayRecord: string;
    defensiveRating: [] | [number];
    teamId: _TeamId;
    restDays: bigint;
    offensiveRating: [] | [number];
    pointsPerGame: [] | [number];
}): {
    pace?: number;
    recentForm: Array<bigint>;
    homeAwayRecord: string;
    defensiveRating?: number;
    teamId: TeamId;
    restDays: bigint;
    offensiveRating?: number;
    pointsPerGame?: number;
} {
    return {
        pace: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.pace)),
        recentForm: value.recentForm,
        homeAwayRecord: value.homeAwayRecord,
        defensiveRating: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.defensiveRating)),
        teamId: value.teamId,
        restDays: value.restDays,
        offensiveRating: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.offensiveRating)),
        pointsPerGame: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.pointsPerGame))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    homePace: _PaceProfile;
    gameId: _GameId;
    refereeProfile: [] | [_RefereeProfile];
    impliedTotal: [] | [number];
    projectedTotal: [] | [number];
    recentTrends: Array<_ScoringTrend>;
    confidenceReport: [] | [_TotalsConfidenceReport];
    awayPace: _PaceProfile;
    injuryImpact: string;
}): {
    homePace: PaceProfile;
    gameId: GameId;
    refereeProfile?: RefereeProfile;
    impliedTotal?: number;
    projectedTotal?: number;
    recentTrends: Array<ScoringTrend>;
    confidenceReport?: TotalsConfidenceReport;
    awayPace: PaceProfile;
    injuryImpact: string;
} {
    return {
        homePace: value.homePace,
        gameId: value.gameId,
        refereeProfile: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.refereeProfile)),
        impliedTotal: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.impliedTotal)),
        projectedTotal: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.projectedTotal)),
        recentTrends: value.recentTrends,
        confidenceReport: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.confidenceReport)),
        awayPace: value.awayPace,
        injuryImpact: value.injuryImpact
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RefereeProfile): RefereeProfile {
    return {
        overRate: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.overRate)),
        name: value.name,
        avgFoulsPerGame: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.avgFoulsPerGame)),
        avgFreeThrowsPerGame: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.avgFreeThrowsPerGame)),
        tendency: value.tendency,
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    overUnderEdge: string;
    keyFactors: Array<string>;
    reasoning: string;
    score: bigint;
    projectedTotal: [] | [number];
    grade: string;
    recommendation: string;
}): {
    overUnderEdge: string;
    keyFactors: Array<string>;
    reasoning: string;
    score: bigint;
    projectedTotal?: number;
    grade: string;
    recommendation: string;
} {
    return {
        overUnderEdge: value.overUnderEdge,
        keyFactors: value.keyFactors,
        reasoning: value.reasoning,
        score: value.score,
        projectedTotal: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.projectedTotal)),
        grade: value.grade,
        recommendation: value.recommendation
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gameId: _GameId;
    players: Array<_PlayerProp>;
    analysisGeneratedAt: string;
}): {
    gameId: GameId;
    players: Array<PlayerProp>;
    analysisGeneratedAt: string;
} {
    return {
        gameId: value.gameId,
        players: from_candid_vec_n44(_uploadFile, _downloadFile, value.players),
        analysisGeneratedAt: value.analysisGeneratedAt
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    seasonAvgPoints: number;
    player: _Player;
    seasonUsageRate: number;
    matchupDefRating: [] | [number];
    seasonAvgMinutes: number;
    propLines: Array<_PropLine>;
    confidenceReport: [] | [_ConfidenceReport];
    backToBack: boolean;
    recentGames: Array<_PlayerRecentGame>;
    homeAwaySplit: number;
}): {
    seasonAvgPoints: number;
    player: Player;
    seasonUsageRate: number;
    matchupDefRating?: number;
    seasonAvgMinutes: number;
    propLines: Array<PropLine>;
    confidenceReport?: ConfidenceReport;
    backToBack: boolean;
    recentGames: Array<PlayerRecentGame>;
    homeAwaySplit: number;
} {
    return {
        seasonAvgPoints: value.seasonAvgPoints,
        player: value.player,
        seasonUsageRate: value.seasonUsageRate,
        matchupDefRating: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.matchupDefRating)),
        seasonAvgMinutes: value.seasonAvgMinutes,
        propLines: value.propLines,
        confidenceReport: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.confidenceReport)),
        backToBack: value.backToBack,
        recentGames: value.recentGames,
        homeAwaySplit: value.homeAwaySplit
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    keyFactors: Array<string>;
    projectedPoints: [] | [number];
    reasoning: string;
    score: bigint;
    grade: string;
    recommendation: string;
}): {
    keyFactors: Array<string>;
    projectedPoints?: number;
    reasoning: string;
    score: bigint;
    grade: string;
    recommendation: string;
} {
    return {
        keyFactors: value.keyFactors,
        projectedPoints: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.projectedPoints)),
        reasoning: value.reasoning,
        score: value.score,
        grade: value.grade,
        recommendation: value.recommendation
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gamesDate: string;
    isUpcomingDate: boolean;
    games: Array<_Game>;
}): {
    gamesDate: string;
    isUpcomingDate: boolean;
    games: Array<Game>;
} {
    return {
        gamesDate: value.gamesDate,
        isUpcomingDate: value.isUpcomingDate,
        games: from_candid_vec_n54(_uploadFile, _downloadFile, value.games)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BetRecommendation): BetRecommendation {
    return {
        id: value.id,
        status: from_candid_BetStatus_n7(_uploadFile, _downloadFile, value.status),
        result: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.result)),
        homeTeam: value.homeTeam,
        gameResult: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.gameResult)),
        betType: from_candid_BetType_n9(_uploadFile, _downloadFile, value.betType),
        gameId: value.gameId,
        description: value.description,
        reasoning: value.reasoning,
        updatedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.updatedAt)),
        recommendedAt: value.recommendedAt,
        awayTeam: value.awayTeam,
        gameDate: value.gameDate,
        preGameOdds: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.preGameOdds)),
        confidence: value.confidence,
        closingLine: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.closingLine)),
        clvScore: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.clvScore)),
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gameTotal: null;
} | {
    playerProp: null;
} | {
    spread: null;
}): BetType {
    return "gameTotal" in value ? BetType.gameTotal : "playerProp" in value ? BetType.playerProp : "spread" in value ? BetType.spread : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GameInvestigation;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: GameInvestigation;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GameInvestigation_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n26(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    final: null;
} | {
    scheduled: null;
} | {
    inProgress: null;
} | {
    postponed: null;
}): GameStatus {
    return "final" in value ? GameStatus.final : "scheduled" in value ? GameStatus.scheduled : "inProgress" in value ? GameStatus.inProgress : "postponed" in value ? GameStatus.postponed : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    networkError: string;
} | {
    notFound: string;
} | {
    parseError: string;
} | {
    rateLimited: string;
} | {
    unavailable: string;
}): {
    __kind__: "networkError";
    networkError: string;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "parseError";
    parseError: string;
} | {
    __kind__: "rateLimited";
    rateLimited: string;
} | {
    __kind__: "unavailable";
    unavailable: string;
} {
    return "networkError" in value ? {
        __kind__: "networkError",
        networkError: value.networkError
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "parseError" in value ? {
        __kind__: "parseError",
        parseError: value.parseError
    } : "rateLimited" in value ? {
        __kind__: "rateLimited",
        rateLimited: value.rateLimited
    } : "unavailable" in value ? {
        __kind__: "unavailable",
        unavailable: value.unavailable
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GameTotal;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: GameTotal;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GameTotal_n30(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n26(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_OddsLine>;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: Array<OddsLine>;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n20(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n26(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PlayerPropsAnalysis;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: PlayerPropsAnalysis;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PlayerPropsAnalysis_n42(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n26(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GamesResponse;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: GamesResponse;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GamesResponse_n52(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n26(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n26(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: _ApiError;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: ApiError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ApiError_n26(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    lost: null;
} | {
    push: null;
}): BetStatus {
    return "won" in value ? BetStatus.won : "cancelled" in value ? BetStatus.cancelled : "pending" in value ? BetStatus.pending : "lost" in value ? BetStatus.lost : "push" in value ? BetStatus.push : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OddsLine>): Array<OddsLine> {
    return value.map((x)=>from_candid_OddsLine_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BetRecommendation>): Array<BetRecommendation> {
    return value.map((x)=>from_candid_BetRecommendation_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerProp>): Array<PlayerProp> {
    return value.map((x)=>from_candid_PlayerProp_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Game>): Array<Game> {
    return value.map((x)=>from_candid_Game_n16(_uploadFile, _downloadFile, x));
}
function to_candid_BetRecommendation_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BetRecommendation): _BetRecommendation {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_BetStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BetStatus): _BetStatus {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_BetType_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BetType): _BetType {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BetRecommendation): _BetRecommendation {
    return {
        id: value.id,
        status: to_candid_BetStatus_n57(_uploadFile, _downloadFile, value.status),
        result: value.result ? candid_some(value.result) : candid_none(),
        homeTeam: value.homeTeam,
        gameResult: value.gameResult ? candid_some(value.gameResult) : candid_none(),
        betType: to_candid_BetType_n59(_uploadFile, _downloadFile, value.betType),
        gameId: value.gameId,
        description: value.description,
        reasoning: value.reasoning,
        updatedAt: value.updatedAt ? candid_some(value.updatedAt) : candid_none(),
        recommendedAt: value.recommendedAt,
        awayTeam: value.awayTeam,
        gameDate: value.gameDate,
        preGameOdds: value.preGameOdds ? candid_some(value.preGameOdds) : candid_none(),
        confidence: value.confidence,
        closingLine: value.closingLine ? candid_some(value.closingLine) : candid_none(),
        clvScore: value.clvScore !== undefined ? candid_some(value.clvScore) : candid_none(),
    };
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BetStatus): {
    won: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    lost: null;
} | {
    push: null;
} {
    return value == BetStatus.won ? {
        won: null
    } : value == BetStatus.cancelled ? {
        cancelled: null
    } : value == BetStatus.pending ? {
        pending: null
    } : value == BetStatus.lost ? {
        lost: null
    } : value == BetStatus.push ? {
        push: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BetType): {
    gameTotal: null;
} | {
    playerProp: null;
} | {
    spread: null;
} {
    return value == BetType.gameTotal ? {
        gameTotal: null
    } : value == BetType.playerProp ? {
        playerProp: null
    } : value == BetType.spread ? {
        spread: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
